package com.geekbrains.common;

public enum Commands {
    TRANSFER_FILE_NOTIFICATION,
    TRANSFER_FILE_READY,
    TRANSFER_FILE_OK,
    DATA_STRUCTURE_REQUEST,
    DATA_STRUCTURE_RESPONSE,
    RECEIVE_FILE_REQUEST_INFO,
    RECEIVE_FILE_INFO,
    RECEIVE_FILE_READY,
    RECEIVE_FILE_OK,
    RENAME_REQUEST,
    RENAME_RESPONSE,
    DELETE_REQUEST,
    DELETE_RESPONSE,
    MKDIR_REQUEST,
    MKDIR_RESPONSE,
    AUTH_REQUEST,
    AUTH_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE
}
